### ISSUE TITLE
Crash iterating over sys.modules: RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by gward** [miketeo/PyMuTester#1]
I just tried mutester for the first time. It crashed right out of the gate:

<pre>
$ PYTHONPATH=lib mutant-nosetests --mutant-path $PWD/lib -w tests
...........
----------------------------------------------------------------------
Ran 11 tests in 1.455s

OK

*************************
Starting mutation test...
*************************
Traceback (most recent call last):
  File "/var/lib/venv/renesys/bin/mutant-nosetests", line 7, in <module>
    main()
  File "/var/lib/venv/renesys/local/lib/python2.7/site-packages/mutester/nose_main.py", line 36, in main
    for module_name, module in sys.modules.iteritems():
RuntimeError: dictionary changed size during iteration
</pre>

**Comment by gward** [comment]
This is version 0.1.0 from pypi, installed into a virtualenv with pip.

**Comment by npandita19** [comment]
@gward were u able to get around this issue? Or was there a fix provided?
@miketeo was there a fix provided?

**Comment by gward** [comment]
@npandita19 No. I tried PyMuTest just once. It crashed, I reported this bug, and moved on to other things.

**Comment by miketeo** [comment]
@npandita19 : I have uploaded a fix under commit 8e8b9e365f65c169f42115d58698771faf333946
It will be really helpful if you can checkout and test it to see if it fixes the error.

**Comment by npandita19** [comment]
@miketeo Thanks for the quick fix! I do not see the crash anymore. But I still, do not have the mutation results. Below is the output for one my experiments. The process ends after printing "*** IFNOT-1...". I do not see any mutation results as shown in the example on https://miketeo.net/wp/index.php/projects/python-mutant-testing-pymutester
Any idea why this could be happening?

$mutant-nosetests --mutant-path astmonkey/ -w astmonkey/tests/
......................S..S.......................S...S......S.........S
----------------------------------------------------------------------
Ran 71 tests in 1.272s

OK (SKIP=6)

*************************
Starting mutation test...
*************************
Mutating SourceGeneratorNodeVisitor.visit_Pass (MY_PATH\astmonkey-master\astmonkey\visitors.py:317)...
Mutating SourceGeneratorNodeVisitor.visit_Call (MY_PATH\astmonkey-master\astmonkey\visitors.py:357)...
*** IFNOT-1...
