### ISSUE TITLE
PyMuTester crash!

### ISSUE THREAD

**Issue by npandita19** [miketeo/PyMuTester#4]
@miketeo Is the below error a usage issue or an existing bug? 

$ mutant-nosetests --mutant-path bitstring-master/ -w bitstring-master/test/
...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 483 tests in 39.871s

OK

*************************
Starting mutation test...
*************************
Traceback (most recent call last):
  File "C:/Python27/Scripts/mutant-nosetests", line 4, in <module>
    __import__('pkg_resources').run_script('pymutester==0.1.1', 'mutant-nosetests')
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1497, in run_script
    exec(code, namespace, namespace)
  File "c:\python27\lib\site-packages\pymutester-0.1.1-py2.7.egg\EGG-INFO\scripts\mutant-nosetests", line 7, in <module>
    main()
  File "C:\Python27\lib\site-packages\pymutester-0.1.1-py2.7.egg\mutester\nose_main.py", line 52, in main
    source_function_names[source_filename] = generate_function_names(source_filename)
  File "C:\Python27\lib\site-packages\pymutester-0.1.1-py2.7.egg\mutester\util.py", line 54, in generate_function_names
    with open(source_filename, 'rU') as fh:
IOError: [Errno 22] invalid mode ('rU') or filename: '<string>'

**Comment by miketeo** [comment]
@npandita19 : rU is a valid mode, so issue could be with your function names.

Pls avoid using sensational titles for your issue that do not describe the errors. I will close such issues immediately.
